name: Deployment

on:
  push:
    branches:
      - release**
    paths:
      - stockmanagementsystem-frontend/**
      - .github/workflows/frontend**
      
jobs:
  deploy_to_heroku_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
       
      - name: Deploy branch ${{ steps.extract_branch.outputs.branch }} to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_FE}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: stockmanagementsystem-frontend
          branch: ${{ steps.extract_branch.outputs.branch }}
          remote_branch: "main"
          procfile: "web: npm install && npm start"
