name: Deployment

on:
  push:
    branches:
      - release**
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_BE}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: StockManagementSystem
