name: Deployment

on:
  push:
    branches:
      - release**
      
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          distribution: 'adopt'
      - name: Build with Maven
        run: cd StockManagementSystem && mvn -B package --file pom.xml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Heroku
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_BE}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: StockManagementSystem
